name: AdvancementBlocker
version: '${project.version}'
main: plugin.advancementblocker.AdvancementBlocker
api-version: '1.20'

commands:
  advblock:
    permission: op
    description: "The main command for the plugin"
    aliases:
      - ab